// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace OvernightPrintsSpecTests.FFs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Basket_Feature")]
    public partial class Basket_FeatureFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Basket_Feature.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Basket_Feature", "In order to add items in the basket\r\nAs a user\r\nI want to have \'Basket Feature\' f" +
                    "eature\r\nSo that I can add items in the basket using products offered", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check Basket state without action with basket")]
        public virtual void CheckBasketStateWithoutActionWithBasket()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Basket state without action with basket", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.And("I navigate to url \"https://www.overnightprints.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("I click CART button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 13
 testRunner.And("I see notification message \"Your shopping cart is empty.\" on the \"Basket Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check Basket state when user added item in the Basket and logout of the system")]
        public virtual void CheckBasketStateWhenUserAddedItemInTheBasketAndLogoutOfTheSystem()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Basket state when user added item in the Basket and logout of the system", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.And("I navigate to url \"https://www.overnightprints.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("I click CART button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.And("I delete items from the basket if they exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.When("I click Log in button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "Email Address",
                        "autestomation@gmail.com"});
            table1.AddRow(new string[] {
                        "Password",
                        "4sep98MPcalifUSA"});
#line 24
 testRunner.And("I set following parameters on Login popup", ((string)(null)), table1, "And ");
#line 28
 testRunner.And("I click Log in button on Login popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.Then("I see element My Account on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.And("I see that user \"Test\" is logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.When("I click Continue Shopping button on Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.Then("I see Main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 37
 testRunner.When("I click Create Business Cards button on Main Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.And("I click Get Started button on \"Business Cards\" Product page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("I click Customize button on \"Business Cards\" Template page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I click Next button on \"Business Cards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("I click Approve button on \"Business Cards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.Then("I wait for 50 seconds for \"Approve Order Page\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
 testRunner.When("I click Continue Order button on \"Business Cards\" Approve Order Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 47
 testRunner.And("I wait for 10 seconds for \"500 Double Sided Business Cards\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table2.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$27.95"});
#line 48
 testRunner.And("I see following product on the Cart", ((string)(null)), table2, "And ");
#line 51
 testRunner.And("I see Basket contains \"1\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.When("I click Back to shopping button on Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.Then("I see Main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
 testRunner.When("I click Create Postcards button on Main Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
 testRunner.And("I click Get Started button on \"Postcards\" Product page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("I click Customize button on \"Postcards\" Template page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I click Next button on \"Postcards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("I click Approve button on \"Postcards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.And("I click Skip button on \"Postcards\" Mailing List Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
 testRunner.Then("I wait for 50 seconds for \"Approve Order Page\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 64
 testRunner.When("I click Continue Order button on \"Postcards\" Approve Order Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 67
 testRunner.And("I wait for 10 seconds for \"500 Double Sided Business Cards\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.And("I wait for 10 seconds for \"1000 Double Sided\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table3.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$27.95"});
            table3.AddRow(new string[] {
                        "1000 Double Sided",
                        "$126.45",
                        "$0.00",
                        "$92.22"});
#line 69
 testRunner.And("I see following product on the Cart", ((string)(null)), table3, "And ");
#line 73
 testRunner.And("I see Basket contains \"2\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.When("I click Log out button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
 testRunner.Then("I see Main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
 testRunner.And("I see that user is not logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.When("I click CART button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
 testRunner.And("I wait for 10 seconds for \"500 Double Sided Business Cards\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.And("I wait for 10 seconds for \"1000 Double Sided\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table4.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$29.35"});
            table4.AddRow(new string[] {
                        "1000 Double Sided",
                        "$126.45",
                        "$0.00",
                        "$98.95"});
#line 83
 testRunner.And("I see following product on the Cart", ((string)(null)), table4, "And ");
#line 87
 testRunner.And("I see Basket contains \"2\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check Basket state when login user added item in the basket, logout, remove item " +
            "from basket and login")]
        public virtual void CheckBasketStateWhenLoginUserAddedItemInTheBasketLogoutRemoveItemFromBasketAndLogin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Basket state when login user added item in the basket, logout, remove item " +
                    "from basket and login", ((string[])(null)));
#line 89
this.ScenarioSetup(scenarioInfo);
#line 90
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 91
 testRunner.And("I navigate to url \"https://www.overnightprints.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
 testRunner.And("I click CART button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 95
 testRunner.And("I delete items from the basket if they exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 97
 testRunner.When("I click Log in button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Email Address",
                        "autestomation@gmail.com"});
            table5.AddRow(new string[] {
                        "Password",
                        "4sep98MPcalifUSA"});
#line 98
 testRunner.And("I set following parameters on Login popup", ((string)(null)), table5, "And ");
#line 102
 testRunner.And("I click Log in button on Login popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 104
 testRunner.Then("I see element My Account on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 105
 testRunner.And("I see that user \"Test\" is logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
 testRunner.And("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.When("I click Continue Shopping button on Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 109
 testRunner.Then("I see Main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 111
 testRunner.When("I click Create Business Cards button on Main Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 112
 testRunner.And("I click Get Started button on \"Business Cards\" Product page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.And("I click Customize button on \"Business Cards\" Template page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 114
 testRunner.And("I click Next button on \"Business Cards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.And("I click Approve button on \"Business Cards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.Then("I wait for 50 seconds for \"Approve Order Page\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 118
 testRunner.When("I click Continue Order button on \"Business Cards\" Approve Order Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 120
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 121
 testRunner.And("I wait for 10 seconds for \"500 Double Sided Business Cards\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table6.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$27.95"});
#line 122
 testRunner.And("I see following product on the Cart", ((string)(null)), table6, "And ");
#line 125
 testRunner.And("I see Basket contains \"1\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 127
 testRunner.When("I click Back to shopping button on Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 128
 testRunner.Then("I see Main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 130
 testRunner.When("I click Create Postcards button on Main Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 131
 testRunner.And("I click Get Started button on \"Postcards\" Product page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
 testRunner.And("I click Customize button on \"Postcards\" Template page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 133
 testRunner.And("I click Next button on \"Postcards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 134
 testRunner.And("I click Approve button on \"Postcards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 135
 testRunner.And("I click Skip button on \"Postcards\" Mailing List Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 137
 testRunner.Then("I wait for 50 seconds for \"Approve Order Page\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 138
 testRunner.When("I click Continue Order button on \"Postcards\" Approve Order Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 140
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 141
 testRunner.And("I wait for 10 seconds for \"500 Double Sided Business Cards\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
 testRunner.And("I wait for 10 seconds for \"1000 Double Sided\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table7.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$27.95"});
            table7.AddRow(new string[] {
                        "1000 Double Sided",
                        "$126.45",
                        "$0.00",
                        "$92.22"});
#line 143
 testRunner.And("I see following product on the Cart", ((string)(null)), table7, "And ");
#line 147
 testRunner.And("I see Basket contains \"2\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
 testRunner.When("I click Log out button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 150
 testRunner.Then("I see Main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 151
 testRunner.And("I see that user is not logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 153
 testRunner.When("I click CART button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 154
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 155
 testRunner.And("I wait for 10 seconds for \"500 Double Sided Business Cards\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 156
 testRunner.And("I wait for 10 seconds for \"1000 Double Sided\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table8.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$29.35"});
            table8.AddRow(new string[] {
                        "1000 Double Sided",
                        "$126.45",
                        "$0.00",
                        "$98.95"});
#line 157
 testRunner.And("I see following product on the Cart", ((string)(null)), table8, "And ");
#line 161
 testRunner.And("I see Basket contains \"2\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 163
 testRunner.When("I remove \"500 Double Sided Business Cards\" item from basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 164
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 165
 testRunner.Then("I wait for 10 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table9.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$29.35"});
#line 166
 testRunner.Then("I don\'t see following product on the Cart", ((string)(null)), table9, "Then ");
#line 169
 testRunner.And("I see Basket contains \"1\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 171
 testRunner.When("I remove \"1000 Double Sided\" item from basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 172
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 173
 testRunner.Then("I wait for 10 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table10.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$29.35"});
            table10.AddRow(new string[] {
                        "1000 Double Sided",
                        "$126.45",
                        "$0.00",
                        "$98.95"});
#line 174
 testRunner.Then("I don\'t see following product on the Cart", ((string)(null)), table10, "Then ");
#line 178
 testRunner.And("I see Basket contains \"0\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
 testRunner.When("I click Log in button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table11.AddRow(new string[] {
                        "Email Address",
                        "autestomation@gmail.com"});
            table11.AddRow(new string[] {
                        "Password",
                        "4sep98MPcalifUSA"});
#line 181
 testRunner.And("I set following parameters on Login popup", ((string)(null)), table11, "And ");
#line 185
 testRunner.And("I click Log in button on Login popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 187
 testRunner.Then("I see that user \"Test\" is logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 188
 testRunner.And("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.And("I see notification message \"Your shopping cart is empty.\" on the \"Basket Page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check Basket state after decline option \"Professional File Review\"")]
        public virtual void CheckBasketStateAfterDeclineOptionProfessionalFileReview()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Basket state after decline option \"Professional File Review\"", ((string[])(null)));
#line 191
this.ScenarioSetup(scenarioInfo);
#line 192
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 193
 testRunner.And("I navigate to url \"https://www.overnightprints.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 194
 testRunner.And("I click CART button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 196
 testRunner.When("I click Continue Shopping button on Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 197
 testRunner.Then("I see Main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 199
 testRunner.When("I click Create Business Cards button on Main Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 200
 testRunner.And("I click Get Started button on \"Business Cards\" Product page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 201
 testRunner.And("I click Customize button on \"Business Cards\" Template page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 202
 testRunner.And("I click Next button on \"Business Cards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 203
 testRunner.And("I click Approve button on \"Business Cards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 205
 testRunner.Then("I wait for 50 seconds for \"Approve Order Page\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 206
 testRunner.When("I click Continue Order button on \"Business Cards\" Approve Order Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 208
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 209
 testRunner.And("I wait for 10 seconds for \"500 Double Sided Business Cards\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table12.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$29.35"});
#line 210
 testRunner.And("I see following product on the Cart", ((string)(null)), table12, "And ");
#line 213
 testRunner.And("I see Basket contains \"1\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 214
 testRunner.When("I click Professional File Review Decline button on Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 216
 testRunner.Then("I wait for 10 seconds for \"Order Summery Block\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table13.AddRow(new string[] {
                        "Order SubTotal price",
                        "$39.95"});
            table13.AddRow(new string[] {
                        "Total price",
                        "$29.35"});
#line 217
 testRunner.And("I see the following properties in the shopping cart", ((string)(null)), table13, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check Basket state after change product parameters on the basket")]
        [NUnit.Framework.TestCaseAttribute("Quantity", "25", "Quantity Price", "$7.15", "$6.24", null)]
        [NUnit.Framework.TestCaseAttribute("Material", "Sandwich", "Material Price", "$363.15", "$151.12", null)]
        public virtual void CheckBasketStateAfterChangeProductParametersOnTheBasket(string property, string value, string price, string realOrderSubtotalPrice, string realTotalPrice, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Basket state after change product parameters on the basket", exampleTags);
#line 222
this.ScenarioSetup(scenarioInfo);
#line 223
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 224
 testRunner.And("I navigate to url \"https://www.overnightprints.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 225
 testRunner.And("I click CART button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 227
 testRunner.When("I click Continue Shopping button on Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 228
 testRunner.Then("I see Main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 230
 testRunner.When("I click Create Business Cards button on Main Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 231
 testRunner.And("I click Get Started button on \"Business Cards\" Product page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 232
 testRunner.And("I click Customize button on \"Business Cards\" Template page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
 testRunner.And("I click Next button on \"Business Cards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.And("I click Approve button on \"Business Cards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
 testRunner.Then("I wait for 50 seconds for \"Approve Order Page\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 237
 testRunner.When("I click Continue Order button on \"Business Cards\" Approve Order Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 239
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 240
 testRunner.And("I wait for 10 seconds for \"500 Double Sided Business Cards\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table14.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$29.35"});
#line 241
 testRunner.And("I see following product on the Cart", ((string)(null)), table14, "And ");
#line 244
 testRunner.And("I see Basket contains \"1\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 246
 testRunner.When(string.Format("I click {0} dropDownMenu and choose \"{1}\" value on Basket Page", property, value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 247
 testRunner.Then("I wait for 10 seconds for \"Order Summery Block\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table15.AddRow(new string[] {
                        "Order SubTotal price",
                        string.Format("{0}", realOrderSubtotalPrice)});
            table15.AddRow(new string[] {
                        "Professional File Review",
                        "$1.00"});
            table15.AddRow(new string[] {
                        "Total price",
                        string.Format("{0}", realTotalPrice)});
#line 248
 testRunner.And("I see the following properties in the shopping cart", ((string)(null)), table15, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check Basket state after change shipping option")]
        [NUnit.Framework.TestCaseAttribute("2 Day Shipping", "2 Day Shipping price", "$21.55", "$51.90", null)]
        [NUnit.Framework.TestCaseAttribute("BITGIT", "Bit Git price", "$43.42", "$73.77", null)]
        public virtual void CheckBasketStateAfterChangeShippingOption(string shippingDescription, string shippingPriceLocator, string realShippingPrice, string realTotalPrice, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Basket state after change shipping option", exampleTags);
#line 259
this.ScenarioSetup(scenarioInfo);
#line 260
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 261
 testRunner.And("I navigate to url \"https://www.overnightprints.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 262
 testRunner.And("I click CART button on the Header Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 264
 testRunner.When("I click Continue Shopping button on Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 265
 testRunner.Then("I see Main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 267
 testRunner.When("I click Create Business Cards button on Main Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 268
 testRunner.And("I click Get Started button on \"Business Cards\" Product page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 269
 testRunner.And("I click Customize button on \"Business Cards\" Template page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 270
 testRunner.And("I click Next button on \"Business Cards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 271
 testRunner.And("I click Approve button on \"Business Cards\" Builder page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 273
 testRunner.Then("I wait for 50 seconds for \"Approve Order Page\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 274
 testRunner.When("I click Continue Order button on \"Business Cards\" Approve Order Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 276
 testRunner.Then("I see Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 277
 testRunner.And("I wait for 10 seconds for \"500 Double Sided Business Cards\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Quantity Price",
                        "Material Price",
                        "Item Subtotal"});
            table16.AddRow(new string[] {
                        "500 Double Sided Business Cards",
                        "$39.95",
                        "$0.00",
                        "$29.35"});
#line 278
 testRunner.And("I see following product on the Cart", ((string)(null)), table16, "And ");
#line 281
 testRunner.And("I see Basket contains \"1\" elements", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 283
 testRunner.When("I set Shipping Zip Code \"99577\" on the Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 284
 testRunner.And("I click Apply Zip Code button on Basket Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 286
 testRunner.Then("I wait for 20 seconds for \"Order Summery Block\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 287
 testRunner.When(string.Format("I click {0} button on Basket Page", shippingDescription), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 289
 testRunner.Then("I wait for 15 seconds for \"Order Summery Block\" is load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table17.AddRow(new string[] {
                        "Order SubTotal price",
                        "$39.95"});
            table17.AddRow(new string[] {
                        "Professional File Review",
                        "$1.00"});
            table17.AddRow(new string[] {
                        "Total price",
                        string.Format("{0}", realTotalPrice)});
            table17.AddRow(new string[] {
                        string.Format("{0}", shippingPriceLocator),
                        string.Format("{0}", realShippingPrice)});
#line 290
 testRunner.And("I see the following properties in the shopping cart", ((string)(null)), table17, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
